import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, utimesSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { execSync } from "child_process";
import { checkStaleness } from "./staleness.js";

function git(cwd: string, args: string) {
  execSync(`git ${args}`, {
    cwd,
    stdio: ["pipe", "pipe", "pipe"],
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: "t",
      GIT_AUTHOR_EMAIL: "t@t",
      GIT_COMMITTER_NAME: "t",
      GIT_COMMITTER_EMAIL: "t@t",
    },
  });
}

describe("checkStaleness", () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), "briefed-stale-"));
    git(root, "init -q");
    git(root, "-c commit.gpgsign=false config commit.gpgsign false");
    writeFileSync(join(root, "src.ts"), "export const x = 1;\n");
    git(root, "add -A");
    git(root, "-c commit.gpgsign=false commit -q -m initial");
    mkdirSync(join(root, ".briefed"), { recursive: true });
    writeFileSync(
      join(root, ".briefed", "index.json"),
      JSON.stringify({ modules: [{ files: ["src.ts"] }] })
    );
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it("reports fresh when no source files changed", () => {
    const report = checkStaleness(root);
    expect(report.isStale).toBe(false);
    expect(report.changedFiles).toBe(0);
  });

  it("ignores .briefed/ hook files generated by init itself", () => {
    // Simulate `briefed init` writing its own runtime hook scripts.
    // These must NOT count as stale source files.
    mkdirSync(join(root, ".briefed", "hooks"), { recursive: true });
    for (const name of [
      "post-edit.js",
      "post-read.js",
      "prompt-submit.js",
      "session-start.js",
      "session-stop.js",
    ]) {
      writeFileSync(join(root, ".briefed", "hooks", name), "// hook\n");
    }

    const report = checkStaleness(root);
    expect(report.isStale).toBe(false);
    expect(report.changedFiles).toBe(0);
  });

  it("ignores .claude/, dist/, build/, and node_modules/ changes", () => {
    for (const dir of [".claude", "dist", "build", "node_modules"]) {
      mkdirSync(join(root, dir), { recursive: true });
      writeFileSync(join(root, dir, "x.js"), "// generated\n");
    }
    const report = checkStaleness(root);
    expect(report.isStale).toBe(false);
    expect(report.changedFiles).toBe(0);
  });

  it("flags real source-file changes", () => {
    // Backdate index.json so subsequent writes are unambiguously newer.
    const past = new Date(Date.now() - 60_000);
    utimesSync(join(root, ".briefed", "index.json"), past, past);

    // Modify the indexed source file and write enough new ones to trip the
    // >5 staleness threshold.
    writeFileSync(join(root, "src.ts"), "export const x = 2;\n");
    for (let i = 0; i < 6; i++) {
      writeFileSync(join(root, `extra${i}.ts`), `export const y${i} = ${i};\n`);
    }
    const report = checkStaleness(root);
    expect(report.isStale).toBe(true);
    expect(report.changedFiles).toBeGreaterThan(5);
  });
});
