import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

/**
 * Generate a GitHub Action workflow that auto-updates briefed context on PRs.
 */
export function generateGitHubAction(root: string) {
  const workflowDir = join(root, ".github", "workflows");
  if (!existsSync(workflowDir)) mkdirSync(workflowDir, { recursive: true });

  const workflow = `# Auto-update briefed context on pushes to main
# Generated by briefed — regenerate with: npx briefed ci
name: Update briefed context

on:
  push:
    branches: [main, master]
    paths:
      - 'src/**'
      - 'lib/**'
      - 'app/**'
      - 'packages/**'
      - '*.ts'
      - '*.js'
      - '*.py'
      - '*.go'
      - '*.rs'

jobs:
  update-context:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for git log

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run briefed init
        run: npx briefed@latest init --skip-hooks

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet CLAUDE.md .claude/rules/ .briefed/ 2>/dev/null || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit updated context
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "briefed[bot]"
          git config user.email "briefed[bot]@users.noreply.github.com"
          git add CLAUDE.md .claude/rules/ .briefed/
          git commit -m "chore: update briefed context [skip ci]"
          git push
`;

  writeFileSync(join(workflowDir, "briefed.yml"), workflow);
}
