import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

/**
 * Generate .cursorrules for Cursor IDE users.
 * Same content as the briefed CLAUDE.md skeleton, formatted for Cursor.
 */
export function writeCursorRules(root: string, skeleton: string, conventions: string) {
  const content = `# Project Context (generated by briefed)
# This file provides Cursor with structural context about this codebase.
# Regenerate with: npx briefed init

${skeleton}

${conventions}
`.trim();

  writeFileSync(join(root, ".cursorrules"), content + "\n");
}

/**
 * Generate AGENTS.md (cross-tool format adopted by multiple AI coding tools).
 * Provides a standardized context file that works with Claude Code, Cursor, Copilot, etc.
 */
export function writeAgentsMd(root: string, skeleton: string, conventions: string) {
  const agentsPath = join(root, "AGENTS.md");

  const BRIEFED_START = "<!-- briefed:agents:start -->";
  const BRIEFED_END = "<!-- briefed:agents:end -->";

  const briefedSection = `${BRIEFED_START}
${skeleton}

${conventions}
${BRIEFED_END}`;

  if (existsSync(agentsPath)) {
    let content = readFileSync(agentsPath, "utf-8");
    if (content.includes(BRIEFED_START)) {
      const startIdx = content.indexOf(BRIEFED_START);
      const endIdx = content.indexOf(BRIEFED_END);
      if (endIdx !== -1) {
        content = content.slice(0, startIdx) + briefedSection + content.slice(endIdx + BRIEFED_END.length);
      }
    } else {
      content = content.trimEnd() + "\n\n" + briefedSection + "\n";
    }
    writeFileSync(agentsPath, content);
  } else {
    writeFileSync(agentsPath, briefedSection + "\n");
  }
}

/**
 * Generate .github/copilot-instructions.md for GitHub Copilot.
 */
export function writeCopilotInstructions(root: string, skeleton: string, conventions: string) {
  const ghDir = join(root, ".github");
  if (!existsSync(ghDir)) mkdirSync(ghDir, { recursive: true });

  const filePath = join(ghDir, "copilot-instructions.md");
  const BRIEFED_START = "<!-- briefed:copilot:start -->";
  const BRIEFED_END = "<!-- briefed:copilot:end -->";

  const section = `${BRIEFED_START}
# Project Context (generated by briefed)

${skeleton}

${conventions}
${BRIEFED_END}`;

  if (existsSync(filePath)) {
    let content = readFileSync(filePath, "utf-8");
    if (content.includes(BRIEFED_START)) {
      const startIdx = content.indexOf(BRIEFED_START);
      const endIdx = content.indexOf(BRIEFED_END);
      if (endIdx !== -1) {
        content = content.slice(0, startIdx) + section + content.slice(endIdx + BRIEFED_END.length);
      }
    } else {
      content = content.trimEnd() + "\n\n" + section + "\n";
    }
    writeFileSync(filePath, content);
  } else {
    writeFileSync(filePath, section + "\n");
  }
}

/**
 * Generate codex.md for OpenAI Codex CLI.
 */
export function writeCodexMd(root: string, skeleton: string, conventions: string) {
  const content = `# Project Context (generated by briefed)

${skeleton}

${conventions}
`.trim();

  writeFileSync(join(root, "codex.md"), content + "\n");
}
